### ISSUE TITLE
Add new ad problem with submitting!

### ISSUE THREAD

**Issue by DobKostadinov** [TeamFeijoa-JsApps/FeijoaCars#6]
After filling the ad form and clicking the add button, the request is not sent and new add is not created. Instead the page reloads and "addNewAd" template is loaded. After filling this template again the data is sent, new ad is created and all user ads are shown. 

Can you fix it?

**Comment by BrunoHautenfaust** [comment]
Everything seems to work fine on my end. I've added 2 ads without problem. Can you double check and let me know if the issue persists?

**Comment by BrunoHautenfaust** [comment]
This issue is present on Chrome. The request gets canceled. After some investigation I found out that the problem was in the template file (_addNewAd.html_). The submit button was inside a form. So when it gets clicked, jQuery onclick fires and at the same time the form's submit fires and things get messed up somehow.
